# Generated by Django 2.2.20 on 2022-04-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改')),
                ('domain', models.CharField(max_length=30, verbose_name='域账号')),
                ('attr', models.CharField(max_length=20, verbose_name='属性名')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '启用'), (1, '禁用')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '- 用户权限',
                'verbose_name_plural': '- 用户权限',
            },
        ),
    ]
