# Generated by Django 2.2.20 on 2021-08-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxtags',
            name='extra',
            field=models.TextField(blank=True, null=True, verbose_name='额外数据'),
        ),
    ]
